alias apu='sudo apt update'
alias apg='sudo apt upgrade'
alias apd='sudo apt dist-upgrade'
alias sup='apu && apg'
alias fup='apu && apg && apd'
alias rup='sudo rpi-update'

alias ycu='sudo yum check-update'
alias yup='sudo yum update'
alias yug='sudo yum upgrade'
alias sup='ycu && yup'
alias fup='ycu && yup && yug'
